### ISSUE TITLE
Cannot import template

### ISSUE THREAD

**Issue by livti** [gcharot/Zabbix#1]
Hi,

I'm having difficulties importing the template, Zabbix 2.4.3 here, it fails to import for me due to a missing trigger:

Trigger "HTTPd process" depends on trigger "ICMP FRONT", which does not exist.

I've checked the template and ICMP FRONT is listed, but I cannot figure out how to solve it (meaning how should I include or create the missing trigger, given that I am unaware of the parameters).

**Comment by gcharot** [comment]
Oups my bad, I let an custom dependency in the template, I guess you just need to remove the dependancy lines from the template an retry the import.

I'll update the template in github as well,
Thanks for the feedback,
Greg

**Comment by gcharot** [comment]
Template updated in git. However I can't test the import so let me know if you have any issue.

Greg
