### ISSUE TITLE
I have error message fro cron

### ISSUE THREAD

**Issue by rmalenko** [gcharot/Zabbix#2]
Hi,
Thank you for the script. 
I have the error message when I run it from cron 
Traceback (most recent call last):
  File "/etc/zabbix/script/zapache.py", line 187, in <module>
    count_request_type(log_line.request_line)
  File "/etc/zabbix/script/zapache.py", line 112, in count_request_type
    if request_type.gro

```
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
* * * * * root /etc/zabbix/script/zapache.py /var/log/apache2/for_zabbix_access.log  # Apache zabbix probe
```

If I run it manually I have no error message
/etc/zabbix/script/zapache.py /var/log/apache2/for_zabbix_access.log

**Comment by gcharot** [comment]
Hello,

That is strange indeed,

Try to enable debug mode and run it manually, check if you have all values poping up especially the GET and POST one.

Also try to run the script via cron with the debug mode and get the output via syslog or file redirection (&> file)

Cheers
