### ISSUE TITLE
Why 0.01667 ?

### ISSUE THREAD

**Issue by zasfe** [gcharot/Zabbix#3]
Hi,
Thank you for the script. 

Sorry My English...

Is the value of the Template formula of the item name .01667 Why ?

Understanding does not go well .

**Comment by gcharot** [comment]
Hi,
Could you be more precise, which script are you executing and what is the value you are talling about ?

Cheers

**Comment by gcharot** [comment]
No answer since two months, closing issue. Please reopen if needed.
