### ISSUE TITLE
Zabbix not display information

### ISSUE THREAD

**Issue by tieungao88** [gcharot/Zabbix#4]
Hi,
I tried to install Zapache. When I launched manually with debug. I saw output information but Information didn't send to Zabbix. Can you suggest me for issues?

Thanks you.

**Comment by gcharot** [comment]
Hello,

You need to double check that your Zabbix agent/server accept active checks. If you get the values when you run the script that probably means you have an issue with your zabbix configuration.

The best thing to do is to try to send data manually via zabbix_sender from your webserver to your zabbix host.

**Things to check :**
- Check your zabbix agent configuration (/etc/zabbix/zabbix_agentd.conf) 

```
Server=yourzabbixserver.example.com
StartAgents=3 (check it is not equal to 0)
Hostname=yourwebserver.example.com (should match your zabbix host declaration)
```
- Check if Zabbix server accepts passive check
- Check if zapache template has been imported and assigne to your web server host.
- Check your zabbix server logs
- Check if you have any iptables rules that can block the traffic
- Google for Zabbix active check configuration

Hope that helps,
Greg

**Comment by tieungao88** [comment]
Hi, 
Thank for reply.
I tried to run manually: 
"[root@zabbix externalscripts]# ./zapache.py /var/log/httpd/access_log >> /home/logabc.txt". 

Then I cat this log file and find out proplem:
" Logtailing file  /var/log/httpd/access_log with offset  /tmp/zapache-logtail.offset sending delta to  /tmp/zapache-logtail.data
Something went wrong while exectuting logtail2 :  [Errno 2] No such file or directory "

Can you suggest me for issues?

Thank you.

**Comment by gcharot** [comment]
It looks like you don't have logtail2 installed, check that you have everything needed to run zapache in the documentation (REQUIREMENTS section).

On Red Hat based distibutions the package is called "logcheck" no sure of the name for Debian based distro. Do a "which" to double check

```
$ which logtail2
/usr/sbin/logtail2
```

CAUTION : As zapache is based on logtail, the first execution will parse your entire log ! This means the first run can take some time depending on your logsize. The next runs will only parse the différence.

Cheers,
Greg

**Comment by tieungao88** [comment]
Hi, 
I installed "logcheck" and "Requirements" on webserver: 
" [root@zabbix ~]# which logtail2 
/usr/sbin/logtail2

When I run direct command. I haven't seen error: 
" [root@zabbix externalscripts]# ./zapache.py /var/log/httpd/access_log"
Logtailing file  /var/log/httpd/access_log with offset  /tmp/zapache-logtail.offset sending delta to  /tmp/zapache-logtail.data
sending key :  apache[ip_count]  - value :  1
sending key :  apache[nr_req]  - value :  758
sending key :  apache[GET]  - value :  350
sending key :  apache[406]  - value :  0
sending key :  apache[405]  - value :  0
sending key :  apache[404]  - value :  0
sending key :  apache[403]  - value :  102

But when I out to log file. I have a problem:
" Logtailing file /var/log/httpd/access_log with offset /tmp/zapache-logtail.offset sending delta to /tmp/zapache-logtail.data
Something went wrong while exectuting logtail2 : [Errno 2] No such file or directory "

Thank you.

**Comment by gcharot** [comment]
Hi,

There is no need to ouput zapache to a file as if you set debug=0 there will be not output to stdout.

Try to execute the commande multiple times without the ">>" and with debug activated.

```
rm -f /tmp/zapache-logtail.offset /tmp/zapache-logtail.data # Purge tmp data
./zapache.py /var/log/httpd/access_log"
_WAIT FOR HTTP REQUESTS_
./zapache.py /var/log/httpd/access_log"
...
```

 If you have new values coming (need traffic on your webserver of course), it means it works and you can turn off the debug output.

If not try to manually run logtail to find the issue :

```
rm -f /tmp/zapache-logtail.offset /tmp/zapache-logtail.data # Purge tmp data
logtail2 -f  /var/log/httpd/access_log  -o /tmp/zapache-logtail.offset > /tmp/zapache-logtail.data
```

Cat the content of /tmp/zapache-logtail.data, it should be the same as  /var/log/httpd/access_log  because we removed the offset. Wait for new requests or make some with curl and rerun the same logtail2 command,  /tmp/zapache-logtail.data should now contain the new requests only.

If you are executing zapache in a cron make sure you export the correct PATH 

```
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
```

Cheers,
Greg

**Comment by tieungao88** [comment]
Hi,
I resolved the problem. The problem is in zabbix-agent config.

Thank you :)

**Comment by tieungao88** [comment]
Hi, 
I resolved the problem. I miss config zabbix_agent. Plugin is very well

Thank you :).
