### ISSUE TITLE
Java 8 support 

### ISSUE THREAD

**Issue by micromachine** [gcharot/Zabbix#5]
Hey Grégory, 
In JDK 8, jstat display Metaspace's statistics, but not PermGen's. So these script did not work properly.

**Comment by gcharot** [comment]
Hello,

Hum, right good to know haven't tried with java 8 at that time. What is the result then, Metaspace replaces PermGen value or everything is broken/shifted ?

Does the alive features still works (jps).

Cheers,
Greg

**Comment by micromachine** [comment]
The output looks like this : 

greg@panoramix:/opt/wildfly/Zabbix/zjstat# ./zjstat.py jboss-modules.jar  alive
1
greg@panoramix:/opt/wildfly/Zabbix/zjstat# 

greg@panoramix:/opt/wildfly/Zabbix/zjstat# ./zjstat.py jboss-modules.jar  all
1
Traceback (most recent call last):
  File "./zjstat.py", line 163, in <module>
    jproc.compute_jstats()              # Compute stats that will be sent to zabbix
  File "./zjstat.py", line 111, in compute_jstats
    self.zdict['perm_used'] = round(float(self.pdict['PU']) \* 1024,2)
KeyError: 'PU'
greg@panoramix:/opt/wildfly/Zabbix/zjstat#

**Comment by gcharot** [comment]
Thanks !
I'll try to support java 8 when i'll get the time.

Cheers,
Greg

**Comment by micromachine** [comment]
Great :) 
If you need support with testing don't hesitate to mail me.

**Comment by gcharot** [comment]
Great thanks for your help and report !

**Comment by ghost** [comment]
Hi,
We did support Java 8 and would like you to send it in the mail.

**Comment by gcharot** [comment]
Hi,

If you don't use JAVA 7 at all you can easily fix the issue yourself. Perm_gen values have been renamed between java 7 & 9, hence the error.

To support JAVA8 (without java 7) please update lines 111 and 112

Line 111

```
Change
        self.zdict['perm_used'] = round(float(self.pdict['PU']) * 1024,2)
to
        self.zdict['perm_used'] = round(float(self.pdict['MU']) * 1024,2)
```

Line 112

```
Change
        self.zdict['perm_max'] = round(float(self.pdict['PGCMX']) * 1024,2)
to
        self.zdict['perm_max'] = round(float(self.pdict['MC']) * 1024,2)
```

I'll soon commit an updated version that will check java version and do the appropriate call.

Thanks to pbobrovnikov for pointing that out.

Cheers,
Greg

**Comment by gcharot** [comment]
Hi,

I just committed a patch for Java 8 support. Please let me know if you encounter any issue.

**Comment by micromachine** [comment]
I will check :)
