### ISSUE TITLE
KeyError: 'CPU'

### ISSUE THREAD

**Issue by ghost** [gcharot/Zabbix#6]
Hi,
I have an error when testing this zstat.py:

root@host:/etc/zabbix/zabbix_agentd.d# sudo -u zabbix /usr/bin/zjstat.py Elasticsearch all
1
Traceback (most recent call last):
  File "/usr/bin/zjstat.py", line 163, in <module>
    jproc.compute_jstats()                              # Compute stats that will be sent to zabbix
  File "/usr/bin/zjstat.py", line 111, in compute_jstats
    self.zdict['perm_used'] = round(float(self.pdict['PU']) \* 1024,2)
KeyError: 'PU'

What is the cause of the error ?

**Comment by gcharot** [comment]
Hello,

Could you please confirm what version of java you are using ? zjstat doesn't support java 8 yet as the jstat command output has changed between version 7 and 8...

You can also set send_to_zabbix = 0 (line 28) to have debug information.

**Comment by ghost** [comment]
Hello,

Yes, I use java version 8. 
I think that instead of the "PU", I can use the parameters "MU" and "MC" ?!

**Comment by gcharot** [comment]
Hello,

I haven't had the chance to have a look at the java 8 jstat output. Not sure how they changed the column names.

These lines are used to compute the values : 

```
    self.zdict['perm_used'] = round(float(self.pdict['PU']) * 1024,2)
    self.zdict['perm_max'] = round(float(self.pdict['PGCMX']) * 1024,2)

    self.zdict['heap_used'] = round(((float(self.pdict['EU']) + float(self.pdict['OU'])) * 1024),2)
    self.zdict['heap_max'] = round(((float(self.pdict['NGCMX']) + float(self.pdict['OGCMX'])) * 1024),2)
```

As you can see :
Perm_used = PU entry
Perm_max = PGCMX
heap_used= EU +OU
heap_max = NGCMX + OGCMX

jstat -gc and jstat -gccapacity commands are used to collect these data. I think you can do a dirty patch pretty easily until I come up with something.

Remember to set send_to_zabbix to 0 for debugging.

Please share if you manage to find the updated value names.

**Comment by gcharot** [comment]
Hi, 

Patch for java 8 is pushed in master branch.

Cheers,
Greg
